using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Rek.ReactJs.Bindings
{
	[Imported]
	[IgnoreNamespace]
	public class ReactDOMInstance
	{
		public ReactClass a;
		public ReactClass abbr;
		public ReactClass address;
		public ReactClass area;
		public ReactClass article;
		public ReactClass aside;
		public ReactClass audio;
		public ReactClass b;
		public ReactClass baseElement;
		public ReactClass bdi;
		public ReactClass bdo;
		public ReactClass big;
		public ReactClass blockquote;
		public ReactClass body;
		public ReactClass br;
		public ReactClass button;
		public ReactClass canvas;
		public ReactClass caption;
		public ReactClass cite;
		public ReactClass code;
		public ReactClass col;
		public ReactClass colgroup;
		public ReactClass data;
		public ReactClass datalist;
		public ReactClass dd;
		public ReactClass del;
		public ReactClass details;
		public ReactClass dfn;
		public ReactClass div;
		public ReactClass dl;
		public ReactClass dt;
		public ReactClass em;
		public ReactClass embed;
		public ReactClass fieldset;
		public ReactClass figcaption;
		public ReactClass figure;
		public ReactClass footer;
		public ReactClass form;
		public ReactClass h1;
		public ReactClass h2;
		public ReactClass h3;
		public ReactClass h4;
		public ReactClass h5;
		public ReactClass h6;
		public ReactClass head;
		public ReactClass header;
		public ReactClass hr;
		public ReactClass html;
		public ReactClass i;
		public ReactClass iframe;
		public ReactClass img;
		public ReactClass input;
		public ReactClass ins;
		public ReactClass kbd;
		public ReactClass keygen;
		public ReactClass label;
		public ReactClass legend;
		public ReactClass li;
		public ReactClass link;
		public ReactClass main;
		public ReactClass map;
		public ReactClass mark;
		public ReactClass menu;
		public ReactClass menuitem;
		public ReactClass meta;
		public ReactClass meter;
		public ReactClass nav;
		public ReactClass noscript;
		public ReactClass objectElement;
		public ReactClass ol;
		public ReactClass optgroup;
		public ReactClass option;
		public ReactClass output;
		public ReactClass p;
		public ReactClass param;
		public ReactClass pre;
		public ReactClass progress;
		public ReactClass q;
		public ReactClass rp;
		public ReactClass rt;
		public ReactClass ruby;
		public ReactClass s;
		public ReactClass samp;
		public ReactClass script;
		public ReactClass section;
		public ReactClass select;
		public ReactClass small;
		public ReactClass source;
		public ReactClass span;
		public ReactClass strong;
		public ReactClass style;
		public ReactClass sub;
		public ReactClass summary;
		public ReactClass sup;
		public ReactClass table;
		public ReactClass tbody;
		public ReactClass td;
		public ReactClass textarea;
		public ReactClass tfoot;
		public ReactClass th;
		public ReactClass thead;
		public ReactClass time;
		public ReactClass title;
		public ReactClass tr;
		public ReactClass track;
		public ReactClass u;
		public ReactClass ul;
		public ReactClass var;
		public ReactClass video;
		public ReactClass wbr;
	}
}